name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AUTHOR_NAME: "${{ github.REPOSITORY_OWNER }}"
  REPOSITORY_NAME: "${{ github.event.repository.name }}"
  REPOSITORY_URL: "https://github.com/${{ github.repository }}"
  BUILD_PATH: "AV1/AVA1/ava1-lista.c"
  README_PATH: "README.md"
  BUILD_DIR: "build"
  EXECUTABLE_NAME: "ava1-lista.exe"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Timestamp
        id: timestamp
        run: |
          timestamp=$(date +'%Y-%m-%d_%H-%M-%S')
          echo "timestamp=$timestamp" >> $GITHUB_ENV

      - name: Set up C compiler
        run: sudo apt-get install -y mingw-w64

      - name: Build
        run: |
          mkdir -p $BUILD_DIR
          x86_64-w64-mingw32-gcc "$BUILD_PATH" -o $BUILD_DIR/$EXECUTABLE_NAME

      - name: Create repository link
        run: |
          echo "$REPOSITORY_URL" > $BUILD_DIR/link-do-repositorio.url

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Create zip release
        run: |
          zip -r ${{ github.workspace }}/${{ env.REPOSITORY_NAME }}__${{ env.AUTHOR_NAME }}__${{ env.TIMESTAMP }}.zip ${{ github.workspace }}/$BUILD_DIR/$EXECUTABLE_NAME ${{ github.workspace }}/$BUILD_DIR/link-do-repositorio.url ${{ github.workspace }}/README.md

      - name: Upload asset
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/${{ env.REPOSITORY_NAME }}__${{ env.AUTHOR_NAME }}__${{ env.TIMESTAMP }}.zip

      - name: Create the Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TIMESTAMP }}
          release_name: ${{ env.TIMESTAMP }}
          body: "Release generated automatically."
          draft: false
          prerelease: false
